
# Added by Chokka 
# Date : 10-07-2026
# docker-compose.yml IaC for React Application.
# HOST_PORT is standardized environment variable declaration.

version: '3.8'

services:
  react-app:
    # Uses the IMAGE_NAME and TAG passed from Jenkins
    image: ${IMAGE_NAME:-react-test-app}:${TAG:-latest}
    container_name: react-test-container
    
    ports:
      - "${HOST_PORT:-8081}:80"
    
    restart: unless-stopped